#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'
networks:
  basic:
    #external:
      #name: postgres-network
services:
  apis:
    container_name: {CONTAINER_NAME}
    image: {CONTAINER_IMAGE}:1.0
    mem_limit: 1000m
    environment:
      - SPRING_PROFILES_ACTIVE={PROFILES_ACTIVE}
    volumes:
      - /opt/deploy/iservice/images:/uploads
    networks:
        - basic
    ports:
      - "127.0.0.1:{PORT}:8383"
